### ISSUE TITLE
tutors-publish-html won't display certain cards on home

### ISSUE THREAD

**Issue by tc-565** [tutors-sdk/tutors#390]
I have been testing https://github.com/tutors-sdk/tutors/pull/388 tutors-publish-html@3.0.1, and I have noticed that the following cards won't display in the root directory of a course when building: github, web, archive and paneltalk (the one that doesn't reside on an unit, course/paneltalk).

These would show when building with tutors-html@2.6.3, so I suspect this could be a regression.

**Comment by tc-565** [comment]
This issue can still be replicated in tutors-publish-html@3.0.2.

**Comment by edeleastar** [comment]
Hi @tc-565 - 3.0.5 should fix this issue. Thanks for the report and please reopen if there is a further issue

**Comment by tc-565** [comment]
I have ran 3.0.5, but I am still having this issue. I have made a new branch in the regression repo to showcase it https://github.com/tc-565/tutors-publish-html-regression-testing/tree/390, with its corresponding run https://github.com/tc-565/tutors-publish-html-regression-testing/actions/runs/5793832681/job/15702299154

**Comment by tc-565** [comment]
P.D. the reopening button is not showing for some reason.

**Comment by edeleastar** [comment]
Hi @tc-565,

thanks for persevering with this. 

tutors-publish-html@3.0.6 now includes root cards of all types, and should work with https://github.com/tc-565/tutors-publish-html-regression-testing/tree/390.

Please note, this is not yet available with the reader.tutors version (tutors-publish)- only on the static generated (tutors-publish-html). I will fix this, but not for a few weeks
